spring:
    kafka:
        producer:
            bootstrap-servers: <ENTER THE BROKERS URL FOR THE CLIENT TO LOOK UP>:9092
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
    port: 8080